services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-docker-network
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testdb?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - my-docker-network
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pw
      MYSQL_ROOT_PASSWORD: rootpw
networks:
  my-docker-network:
